#!/usr/bin/env python3
"""Regenerate every file that restates something written elsewhere.

The instructions are written once:

    AGENTS.md                     the always-on contract — who Jarvis is, the rules, the checklist
    .claude/rules/*.md            the conventions for one artifact type, scoped with `paths:`
    .claude/skills/*/SKILL.md     an operation — the change-request protocol
    schema.yml                    the artifact types

and stamped into the files that need to restate them:

    .github/instructions/*.instructions.md   Copilot's dialect of each rule (`paths:` -> `applyTo:`)
    .github/prompts/*.prompt.md              a door that lets `/change-request` be typed in Copilot
    AGENTS.md                                the artifact type table, from schema.yml
    index.html                               the instructions shown on the landing page

and the history is written once — versions in content/change_log/changeLog.md, assessments as
content/sources/okf_assessment_*.md — and restated as

    content/log.md                           the Open Knowledge Format log (§9): one list entry per
                                             version and per assessment, grouped under its date,
                                             newest first

Why the Copilot copies exist at all: VS Code reads `AGENTS.md` at the workspace root and discovers
skills in `.claude/skills/` directly, so the contract and the protocol need no copy. But the
`.claude/rules` location Copilot supports is user-profile only, so a project's scoped rules must be
restated under `.github/instructions/`; and Copilot matches a skill on its description rather than
on a name you type, so the prompt file is what makes the operation typable. Each prompt names its
skill and stops, so the protocol still exists in exactly one place.

Usage:
    python3 scripts/generate.py            # write
    python3 scripts/generate.py --check    # exit 1 if anything is stale (make build)
"""

from __future__ import annotations

import html
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
AGENTS = ROOT / "AGENTS.md"
RULES = ROOT / ".claude" / "rules"
SKILLS = ROOT / ".claude" / "skills"
COPILOT = ROOT / ".github"
LANDING = ROOT / "index.html"
SCHEMA = ROOT / "schema.yml"
CHANGE_LOG = ROOT / "content" / "change_log" / "changeLog.md"
SOURCES = ROOT / "content" / "sources"
LOG = ROOT / "content" / "log.md"
ASSESSMENT_RE = re.compile(r"okf_assessment_(\d{4})_(\d{2})_(\d{2})(?:_(\d+))?\.md")
VERSION_RE = re.compile(r"^## (v\d+\.\d+) – (.+?) \((\d{4}-\d{2}-\d{2})\)\s*\n+(.+?)\n", re.M)

FRONTMATTER_RE = re.compile(r"\A---\n(.*?)\n---\n?", re.DOTALL)
NOTE = "<!-- GENERATED by scripts/generate.py — do not edit. Edit {source} and run `make generate`. -->"


def split(text: str) -> tuple[dict, str]:
    match = FRONTMATTER_RE.match(text)
    if not match:
        return {}, text
    return yaml.safe_load(match.group(1)) or {}, text[match.end():]


def copilot_files() -> dict[Path, str]:
    out = {}
    for src in sorted(RULES.glob("*.md")):
        meta, body = split(src.read_text(encoding="utf-8"))
        globs = meta.get("paths") or []
        apply_to = ",".join(globs if isinstance(globs, list) else [globs])
        rel = src.relative_to(ROOT).as_posix()
        out[COPILOT / "instructions" / f"{src.stem}.instructions.md"] = (
            f'---\napplyTo: "{apply_to}"\n---\n\n{NOTE.format(source=rel)}\n\n{body.lstrip()}'
        )
    for src in sorted(SKILLS.glob("*/SKILL.md")):
        meta, _ = split(src.read_text(encoding="utf-8"))
        name, rel = src.parent.name, src.relative_to(ROOT).as_posix()
        out[COPILOT / "prompts" / f"{name}.prompt.md"] = (
            f"---\nagent: agent\ndescription: {meta['description']}\n---\n\n"
            f"{NOTE.format(source=rel)}\n\n"
            f"Run the **{name}** operation.\n\n"
            f"Read `{rel}` and follow it exactly, together with `AGENTS.md`. This file is only the\n"
            "door; the skill is the procedure. Anything the user typed after the command is the input.\n"
        )
    return out


def types_table() -> str:
    types = (yaml.safe_load(SCHEMA.read_text(encoding="utf-8")) or {})["types"]
    rows = ["| Type | Where | Rules | Holds |", "|---|---|---|---|"]
    for name, spec in types.items():
        rules = f"`.claude/rules/{spec['rules']}`" if spec.get("rules") else "—"
        rows.append(f"| `{name}` | `content/{spec['where']}` | {rules} | {spec['holds']} |")
    return "\n".join(rows)


def replace_block(text: str, name: str, body: str) -> str:
    pattern = re.compile(rf"(<!--\s*{name}:start[^>]*-->\n).*?(<!--\s*{name}:end\s*-->)", re.DOTALL)
    if not pattern.search(text):
        raise SystemExit(f"generate: no <!-- {name}:start --> block in the target file")
    return pattern.sub(lambda m: m.group(1) + body + "\n" + m.group(2), text)


def landing_page(current: str, agents: str) -> str:
    """The landing page shows the instructions Jarvis runs on, embedded as static Markdown."""
    sources = [("AGENTS.md", agents)]
    sources += [(p.relative_to(ROOT).as_posix(), p.read_text(encoding="utf-8")) for p in sorted(SKILLS.glob("*/SKILL.md"))]
    sources += [(p.relative_to(ROOT).as_posix(), p.read_text(encoding="utf-8")) for p in sorted(RULES.glob("*.md"))]
    parts = []
    for rel, text in sources:
        _, body = split(text)
        body = re.sub(r"<!--.*?-->\n?", "", body, flags=re.DOTALL)  # generated-block markers
        parts.append(f"<p class=\"file-badge\">{html.escape(rel)}</p>\n\n{body.strip()}\n")
    markdown = "\n\n---\n\n".join(parts)
    if "</script" in markdown.lower():
        raise SystemExit("generate: an instruction file contains </script>, which would end the embed early")
    new = re.sub(r'(<script id="raw-md" type="text/markdown">\n).*?(\n  </script>)',
                 lambda m: m.group(1) + markdown + m.group(2), current, count=1, flags=re.DOTALL)
    new = re.sub(r'<div class="file-badge">[^<]*</div>',
                 '<div class="file-badge">AGENTS.md · .claude/skills · .claude/rules</div>', new, count=1)
    return new


def assessment_entries(sources: Path) -> dict[str, list[str]]:
    """One log entry per filed assessment, keyed by the day it ran, the day's later runs first."""
    runs = []
    for path in sources.glob("okf_assessment_*.md"):
        match = ASSESSMENT_RE.fullmatch(path.name)
        if not match:
            raise SystemExit(f"generate: {path.name} is not named okf_assessment_<yyyy>_<mm>_<dd>[_<n>].md")
        meta, _ = split(path.read_text(encoding="utf-8"))
        if not meta.get("title") or not meta.get("description"):
            raise SystemExit(f"generate: {path.name} needs a title and a description for its log entry")
        yyyy, mm, dd, run = match.groups()
        runs.append((f"{yyyy}-{mm}-{dd}", int(run or 1),
                     f"- **Assessment:** [{meta['title']}](sources/{path.name}) — {str(meta['description']).strip()}"))
    groups: dict[str, list[str]] = {}
    for day, _, entry in sorted(runs, key=lambda r: (r[0], r[1]), reverse=True):
        groups.setdefault(day, []).append(entry)
    return groups


def okf_log(change_log: Path = CHANGE_LOG, sources: Path = SOURCES) -> str:
    """content/log.md — the versions and the assessments as the date-grouped list OKF v0.2 §9 specifies.

    Within a day, assessments come first: an assessment checks the documentation as released, so it is
    the newer entry.
    """
    versions = VERSION_RE.findall(change_log.read_text(encoding="utf-8"))
    if not versions:
        raise SystemExit("generate: no `## vX.Y – Title (YYYY-MM-DD)` sections found in the change log")
    groups = assessment_entries(sources)
    for version, title, day, summary in versions:
        groups.setdefault(day, []).append(
            # The summary's own links are relative to the change log's folder, so only their text travels.
            f"- **Release:** [{version} – {title}](change_log/changeLog.md) — {re.sub(r'\[([^\]]+)\]\([^)]+\)', r'\1', summary.strip())}")
    out = ["---", 'title: "Log"', "type: log",
           'description: "Every version of the documentation and every conformance assessment, newest first."',
           "weight: 80", "---", "",
           NOTE.format(source="content/change_log/changeLog.md or file an assessment in content/sources/"),
           "", "# Log", ""]
    for day in sorted(groups, reverse=True):
        out += [f"## {day}", "", *groups[day], ""]
    return "\n".join(out)


def main() -> int:
    check = "--check" in sys.argv[1:]
    wanted = copilot_files()
    agents = replace_block(AGENTS.read_text(encoding="utf-8"), "schema-types", types_table())
    wanted[AGENTS] = agents
    wanted[LANDING] = landing_page(LANDING.read_text(encoding="utf-8"), agents)
    wanted[LOG] = okf_log()

    stale = []
    for existing in sorted((COPILOT / "instructions").glob("*.md")) + sorted((COPILOT / "prompts").glob("*.md")):
        if existing not in wanted:
            stale.append(f"{existing.relative_to(ROOT)} (no source any more)")
            if not check:
                existing.unlink()
    for path, text in wanted.items():
        if path.exists() and path.read_text(encoding="utf-8") == text:
            continue
        stale.append(str(path.relative_to(ROOT)))
        if not check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")

    if check and stale:
        print(f"generate: STALE — run `make generate` ({', '.join(stale)})", file=sys.stderr)
        return 1
    print(f"generate: {'updated ' + ', '.join(stale) if stale else 'up to date'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
